### ISSUE TITLE
The weight inside of the traveler's backpack does not affect the weight.

### ISSUE THREAD

**Issue by jacomenma** [MEGATREX4/inventory-weight#4]
No matter how many spawn eggs I put in, the weight and the weight inside did not change.
When I looked at the creative tab, I saw that the backpack weighed about 1.3k(There is no indication of weight inside), and once I opened the backpack, it was the same indication as the shulker box. This bug may have something to do with a bug in the title.
The mod I used was:
cardinal components API,
cloth config API,
entity culling,
fabric API,
ferritecore,
lithium,
MT inventory weight,
mod menu,
modern fix,
sodium,
traveler's backpack.

**Comment by MEGATREX4** [comment]
thank you for your feedback, the error has been fixed and I am already sending new files to the platforms
after passing Modrinth and CurseForge moderation, you will be able to download the mod with fixes
